import './globals.css'
import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'

// Khởi tạo font từ Google Fonts với biến CSS
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
  display: 'swap',
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
  display: 'swap',
})

// Metadata cho SEO
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// ✅ Component layout gốc
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* 
        suppressHydrationWarning: giúp React không cảnh báo mismatch nhỏ (như class, attribute inject từ extension)
      */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}
      >
        {children}
      </body>
    </html>
  )
}
